from enum import auto

from autoname_enum import AutoNameEnum


class CraftingMaterial(AutoNameEnum):

    ISLAND_ALYSSUM = auto()
    ISLAND_APPLE = auto()
    ISLAND_BRANCH = auto()
    ISLAND_CABBAGE = auto()
    ISLAND_CLAM = auto()
    ISLAND_CLAW = auto()
    ISLAND_CLAY = auto()
    ISLAND_COPPER_ORE = auto()
    ISLAND_CORAL = auto()
    ISLAND_CORN = auto()
    ISLAND_COTTON_BALL = auto()
    ISLAND_HAMMERHEAD = auto()
    ISLAND_HEMP = auto()
    ISLAND_IRON_ORE = auto()
    ISLAND_JELLYFISH = auto()
    ISLAND_LAVER = auto()
    ISLAND_LEUCOGRANITE = auto()
    ISLAND_LIMESTONE = auto()
    ISLAND_LOG = auto()
    ISLAND_ONION = auto()
    ISLAND_PALM_LEAF = auto()
    ISLAND_PALM_LOG = auto()
    ISLAND_PARSNIP = auto()
    ISLAND_POPOTO = auto()
    ISLAND_PUMPKIN = auto()
    ISLAND_QUARTZ = auto()
    ISLAND_RADISH = auto()
    ISLAND_ROCK_SALT = auto()
    ISLAND_SAND = auto()
    ISLAND_SAP = auto()
    ISLAND_SILVER_ORE = auto()
    ISLAND_SPRUCE_LOG = auto()
    ISLAND_SQUID = auto()
    ISLAND_STONE = auto()
    ISLAND_SUGARCANE = auto()
    ISLAND_TINSAND = auto()
    ISLAND_TOMATO = auto()
    ISLAND_VINE = auto()
    ISLAND_WHEAT = auto()
    ISLEBERRY = auto()
    ISLEFISH = auto()
    ISLEWORT = auto()
    RAW_ISLAND_GARNET = auto()
    SANCTUARY_CARAPACE = auto()
    SANCTUARY_CLAW = auto()
    SANCTUARY_EGG = auto()
    SANCTUARY_FANG = auto()
    SANCTUARY_FEATHER = auto()
    SANCTUARY_FLEECE = auto()
    SANCTUARY_FUR = auto()
    SANCTUARY_HORN = auto()
    SANCTUARY_MILK = auto()
